#!/bin/bash

# Define command-line arguments
NAMESPACE=$1
RESOURCE_TYPE=$2

if [ "$#" -ne 2 ]; then
  echo "Usage:          kubectl kubeplugin <namespace> <resource-type>"
  echo ""
  echo "Example:        kubectl kubeplugin kube-system pod"
  exit 1
fi

# Retrieve resource usage statistics from Kubernetes

i=0
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read -r line;
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  # printf "| %-13s | %-21s | %-36s | %-5s | %-6s |\n" "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY"
  if [ $i -eq 0 ]; then
    echo "RESOURCE_TYPE, NAMESPACE, NAME, CPU, MEMORY"
  fi
  ((i++))
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done | column -t -s ','

